package com.myspace.ticketproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Comments implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "Entered Date")
	private java.util.Date ticketCommentEnteredDate;
	@org.kie.api.definition.type.Label(value = "Update At")
	private java.util.Date ticketCommentUpdateAt;
	@org.kie.api.definition.type.Label(value = "Created By")
	private java.lang.String ticketCommentCreatedBy;
	@org.kie.api.definition.type.Label(value = "Updated By")
	private java.lang.String ticketCommentUpdatedBy;
	@org.kie.api.definition.type.Label(value = "Comment")
	private java.lang.String ticketComment;
	@org.kie.api.definition.type.Label(value = "Ticket Id")
	private java.lang.String ticketId;

	public Comments() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.util.Date getTicketCommentEnteredDate() {
		return this.ticketCommentEnteredDate;
	}

	public void setTicketCommentEnteredDate(
			java.util.Date ticketCommentEnteredDate) {
		this.ticketCommentEnteredDate = ticketCommentEnteredDate;
	}

	public java.util.Date getTicketCommentUpdateAt() {
		return this.ticketCommentUpdateAt;
	}

	public void setTicketCommentUpdateAt(java.util.Date ticketCommentUpdateAt) {
		this.ticketCommentUpdateAt = ticketCommentUpdateAt;
	}

	public java.lang.String getTicketCommentCreatedBy() {
		return this.ticketCommentCreatedBy;
	}

	public void setTicketCommentCreatedBy(
			java.lang.String ticketCommentCreatedBy) {
		this.ticketCommentCreatedBy = ticketCommentCreatedBy;
	}

	public java.lang.String getTicketCommentUpdatedBy() {
		return this.ticketCommentUpdatedBy;
	}

	public void setTicketCommentUpdatedBy(
			java.lang.String ticketCommentUpdatedBy) {
		this.ticketCommentUpdatedBy = ticketCommentUpdatedBy;
	}

	public java.lang.String getTicketComment() {
		return this.ticketComment;
	}

	public void setTicketComment(java.lang.String ticketComment) {
		this.ticketComment = ticketComment;
	}

	public java.lang.String getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(java.lang.String ticketId) {
		this.ticketId = ticketId;
	}

	public Comments(java.lang.String id,
			java.util.Date ticketCommentEnteredDate,
			java.util.Date ticketCommentUpdateAt,
			java.lang.String ticketCommentCreatedBy,
			java.lang.String ticketCommentUpdatedBy,
			java.lang.String ticketComment, java.lang.String ticketId) {
		this.id = id;
		this.ticketCommentEnteredDate = ticketCommentEnteredDate;
		this.ticketCommentUpdateAt = ticketCommentUpdateAt;
		this.ticketCommentCreatedBy = ticketCommentCreatedBy;
		this.ticketCommentUpdatedBy = ticketCommentUpdatedBy;
		this.ticketComment = ticketComment;
		this.ticketId = ticketId;
	}

}