package com.myspace.ticketproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ListOfDocuments implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Documents")
	private java.util.List<com.myspace.ticketproject.Documents> documents;

	public ListOfDocuments() {
	}

	public java.util.List<com.myspace.ticketproject.Documents> getDocuments() {
		return this.documents;
	}

	public void setDocuments(
			java.util.List<com.myspace.ticketproject.Documents> documents) {
		this.documents = documents;
	}

	public ListOfDocuments(
			java.util.List<com.myspace.ticketproject.Documents> documents) {
		this.documents = documents;
	}

}